const npr = new Intl.NumberFormat("ne-NP", { style: "currency", currency: "NPR", maximumFractionDigits: 0 });
const amount = (value) => npr.format(value || 0);
function Row({ label, value, emphasis = false }) { return <div className={`flex items-center justify-between gap-3 py-3 ${emphasis ? "border-t border-slate-700 text-base font-semibold text-white" : "text-sm text-slate-300"}`}><span className="min-w-0 break-words">{label}</span><span className="shrink-0 whitespace-nowrap">{amount(value)}</span></div>; }
export default function SalaryResult({ result }) {
  const employeeType = result.employeeType === "permanent" ? "स्थायी कर्मचारी" : "अस्थायी / करार कर्मचारी";
  return <aside className="h-fit min-w-0 rounded-2xl border border-cyan-400/30 bg-slate-900 p-4 shadow-xl sm:p-7">
    <p className="text-sm font-semibold tracking-wider text-cyan-400">अनुमानित हातमा आउने तलब</p><p className="mt-2 text-4xl font-bold text-white">{amount(result.takeHome)}</p><p className="mt-1 text-sm text-slate-400">{employeeType} · प्रति महिना</p>
    <div className="mt-6 divide-y divide-slate-800"><Row label="आधारभूत तलब" value={result.basicSalary} /><Row label={`ग्रेड रकम (${result.gradeNumber} ग्रेड × १ दिनको तलब)`} value={result.gradeAllowance} /><Row label="कार्यसम्पादनमा आधारित प्रोत्साहन भत्ता (आधारभूत + ग्रेडको १०%)" value={result.performanceIncentive} /><Row label="अन्य मासिक भत्ता" value={result.allowances - result.performanceIncentive - result.gradeAllowance} /><Row label="कुल मासिक पारिश्रमिक" value={result.gross} emphasis /><Row label="EPF कट्टी (आधारभूत + ग्रेडको १०%)" value={result.epfEmployee} /><Row label="नागरिक लगानी कोष (CIT) स्वेच्छिक योगदान" value={result.citSelfContribution} /><Row label="सावधिक जीवन बीमा कट्टी" value={result.lifeInsuranceEmployee} /><Row label="अनुमानित मासिक आयकर" value={result.monthlyTax} /><Row label="कुल मासिक कट्टी" value={result.deductions} emphasis /><Row label="खुद मासिक तलब" value={result.takeHome} emphasis /></div>
    <div className="mt-5 rounded-lg border border-cyan-400/20 bg-cyan-400/5 p-4 text-sm text-slate-300"><p className="font-semibold text-cyan-400">कार्यालयको मासिक योगदान (तलबबाट कट्टी हुँदैन)</p><div className="mt-2 divide-y divide-slate-700"><Row label="कार्यालयको EPF योगदान (१०%)" value={result.epfOffice} /><Row label="कार्यालयको सावधिक जीवन बीमा योगदान" value={result.lifeInsuranceOffice} /><Row label="कुल कार्यालय योगदान" value={result.officeContribution} emphasis /></div></div>
    <div className="mt-6 rounded-lg bg-slate-950 p-4 text-xs leading-5 text-slate-400">आधारभूत तलबमान अर्थ मन्त्रालयको २०८३ साउन १ देखि लागू सूचना अनुरूप राखिएको छ। अस्थायी/करार सेवाका भत्ता र कट्टी फरक हुन सक्ने भएकाले आफ्नो कार्यालयबाट पुष्टि गर्नुहोस्।</div>
  </aside>;
}
